services:
  - type: web
    name: ai-iot-tamper-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 app:app
    envVars:
      - key: PORT
        value: 5000
      - key: SECRET_KEY
        generateValue: true
